import React, { useState, useEffect } from "react";

// const api = [
//   {
//     id: 1,
//     name: "task3.2",
//     description: "task3 description user003",
//     priority: "Low",
//     assignee: "Alice Johnson",
//     activities: [
//       {
//         id: 1,
//         name: "save1",
//         department: "qwert",
//         date: "2025-09-04",
//       },
//       {
//         id: 2,
//         name: "activity1.2",
//         department: "digitally",
//         date: "2025-01-03",
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: "task4",
//     description: "task4 description",
//     priority: "High",
//     assignee: "Bob Brown",
//     activities: [
//       {
//         id: 3,
//         name: "lorem123",
//         department: "12345",
//         date: "2025-09-04",
//       },
//       {
//         id: 4,
//         name: "lorem123",
//         department: "12345",
//         date: "2025-09-04",
//       },
//       {
//         id: 5,
//         name: "lorem10",
//         department: "qwert",
//         date: "2025-09-04",
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: "lorem",
//     description: "qwert",
//     priority: "High",
//     assignee: "Jane Smith",
//     activities: [],
//   },
//   {
//     id: 4,
//     name: "lorem",
//     description: "lorem",
//     priority: "High",
//     assignee: "Jane Smith",
//     activities: [],
//   },
// ];

const api = [
  {
    id: 1,
    name: "task3.2",
    description: "task3 description user003",
    priority: "Low",
    assignee: "Alice Johnson",
    activities: [
      { id: 1, name: "save1", department: "qwert", date: "2025-09-04" },
      {
        id: 2,
        name: "activity1.2",
        department: "digitally",
        date: "2025-01-03",
      },
    ],
  },
  {
    id: 2,
    name: "task4",
    description: "task4 description",
    priority: "High",
    assignee: "Bob Brown",
    activities: [
      { id: 3, name: "lorem123", department: "12345", date: "2025-09-04" },
      { id: 4, name: "lorem123", department: "12345", date: "2025-09-04" },
      { id: 5, name: "lorem10", department: "qwert", date: "2025-09-04" },
    ],
  },
  {
    id: 3,
    name: "task5",
    description: "description 5",
    priority: "Medium",
    assignee: "Charlie Davis",
    activities: [],
  },
  {
    id: 4,
    name: "task6",
    description: "description 6",
    priority: "Low",
    assignee: "Diana Evans",
    activities: [],
  },
  {
    id: 5,
    name: "task7",
    description: "description 7",
    priority: "High",
    assignee: "Evan Foster",
    activities: [],
  },
  {
    id: 6,
    name: "task8",
    description: "description 8",
    priority: "Medium",
    assignee: "Grace Hill",
    activities: [],
  },
  {
    id: 7,
    name: "task9",
    description: "description 9",
    priority: "Low",
    assignee: "Henry Ivy",
    activities: [],
  },
  {
    id: 8,
    name: "task10",
    description: "description 10",
    priority: "High",
    assignee: "Irene Jones",
    activities: [],
  },
  {
    id: 9,
    name: "task11",
    description: "description 11",
    priority: "Medium",
    assignee: "Jack King",
    activities: [],
  },
  {
    id: 10,
    name: "task12",
    description: "description 12",
    priority: "Low",
    assignee: "Karen Long",
    activities: [],
  },
  {
    id: 11,
    name: "task13",
    description: "description 13",
    priority: "High",
    assignee: "Liam Moore",
    activities: [],
  },
  {
    id: 12,
    name: "task14",
    description: "description 14",
    priority: "Medium",
    assignee: "Mia Nelson",
    activities: [],
  },
  {
    id: 13,
    name: "task15",
    description: "description 15",
    priority: "Low",
    assignee: "Nina Owens",
    activities: [],
  },
  {
    id: 14,
    name: "task16",
    description: "description 16",
    priority: "High",
    assignee: "Oscar Parker",
    activities: [],
  },
  {
    id: 15,
    name: "task17",
    description: "description 17",
    priority: "Medium",
    assignee: "Paula Quinn",
    activities: [],
  },
  {
    id: 16,
    name: "task18",
    description: "description 18",
    priority: "Low",
    assignee: "Quinn Rivera",
    activities: [],
  },
  {
    id: 17,
    name: "task19",
    description: "description 19",
    priority: "High",
    assignee: "Rosa Smith",
    activities: [],
  },
  {
    id: 18,
    name: "task20",
    description: "description 20",
    priority: "Medium",
    assignee: "Steve Taylor",
    activities: [],
  },
  {
    id: 19,
    name: "task21",
    description: "description 21",
    priority: "Low",
    assignee: "Tina Underwood",
    activities: [],
  },
  {
    id: 20,
    name: "task22",
    description: "description 22",
    priority: "High",
    assignee: "Uma Vaughn",
    activities: [],
  },
  {
    id: 21,
    name: "task23",
    description: "description 23",
    priority: "Medium",
    assignee: "Victor White",
    activities: [],
  },
  {
    id: 22,
    name: "task24",
    description: "description 24",
    priority: "Low",
    assignee: "Wendy Xu",
    activities: [],
  },
  {
    id: 23,
    name: "task25",
    description: "description 25",
    priority: "High",
    assignee: "Xander Young",
    activities: [],
  },
  {
    id: 24,
    name: "task26",
    description: "description 26",
    priority: "Medium",
    assignee: "Yara Zimmerman",
    activities: [],
  },
  {
    id: 25,
    name: "task27",
    description: "description 27",
    priority: "Low",
    assignee: "Zane Allen",
    activities: [],
  },
];

export default api;
